distributable:
  url: https://ftp.gnu.org/gnu/tar/tar-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  - 1.34
  #TODO scrape https://ftp.gnu.org/gnu/tar/

build:
  dependencies:
    tea.xyz/gx/cc: 'c99'
    tea.xyz/gx/make: '*'
  script: |
    ./configure --prefix={{ prefix }} --disable-debug
    make --jobs {{ hw.concurrency }} install

test:
  script:
    tar czvf test.tar.gz {{ prefix }}
