distributable:
  url: https://ftp.gnu.org/gnu/which/which-{{version.raw}}.tar.gz
  strip-components: 1

versions:
  url: https://ftp.gnu.org/gnu/which
  match: /which-\d+(\.\d+)*\.tar\.gz/
  strip:
    - /^which-/
    - /\.tar\.gz$/

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script:
    - ./configure $ARGS
    - make --jobs {{ hw.concurrency }} install
  env:
    ARGS:
      - --prefix="{{prefix}}"
      - --disable-dependency-tracking

provides:
  - bin/which

test: which -a which | grep "{{prefix}}/bin/which"
