distributable:
  url: https://cairographics.org/releases/cairo-{{ version }}.tar.xz
  strip-components: 1

versions:
  - 1.16.0

dependencies:
  tea.xyz/gx/cc: c99
  tea.xyz/gx/make: '*'
  libpng.org: 1
  pixman.org: ^0.40.0
  freetype.org: 2
  gnome.org/glib: 2
  freedesktop.org/fontconfig: 2
  sourceware.org/bzip2: 1

build:
  dependencies:
    freedesktop.org/pkg-config: ^0.29
    libexpat.github.io: 2  #FIXME or fontconfig detection fails
    gnome.org/gobject-introspection: 1
  script: |
    ./configure --prefix={{ prefix }}
    make --jobs {{ hw.concurrency }}
    make install

    if test {{ hw.platform }} == darwin; then
      #FIXME wtf is going on here
      sed -i.bak 's|/opt/libpng.org/v.*/lib/libintl.la||' {{prefix}}/lib/libcairo-gobject.la
    fi

test: true  #FIXME