distributable:
  url: https://download.redis.io/releases/redis-{{ version }}.tar.gz
  strip-components: 1

versions:
  github: redis/redis


provides:
  - bin/redis-server
  - bin/redis-cli
  - bin/redis-benchmark

dependencies:
  openssl.org: ^1

build:
  cores: 2
  dependencies:
    tea.xyz/gx/make: '*'
    freedesktop.org/pkg-config: '>=0.29'
    tea.xyz/gx/cc: c99
  script:
    make install
    # TODO: configure default redis.conf if necessary
  env:
    PREFIX: ${{prefix}}
    BUILD_TLS: yes
test:
  script: |
    redis-server --test-memory 2
    redis-cli --version
    redis-benchmark --version

    redis-server --daemonize yes
    redis-cli --raw SET key123 value123
    redis_value=$(redis-cli --raw GET key123)
    echo $redis_value

    redis-cli shutdown

    if [ $redis_value = "value123" ]; then
      echo "redis works!"
    else
      echo "redis install doesnt work!"
      set -e
    fi
