distributable:
  url: https://github.com/Kitware/CMake/releases/download/v{{ version }}/cmake-{{ version }}.tar.gz
  strip-components: 1

versions:
  github: Kitware/CMake/releases/tags

detect:
  cmd: cmake --version
  regex: cmake version \v

dependencies:
  curl.se: '>=5'
  zlib.net: 1
  sourceware.org/bzip2: 1

provides:
  - bin/cmake
  - bin/ccmake
  - bin/cpack
  - bin/ctest

# TODO
# * --system-libs (provide all deps ourselves)
#     (Zlib, Bzip2, cURL, nghttp2, Expat and libarchive)

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |-
    ./bootstrap \
      --prefix={{ prefix }} \
      --parallel={{ hw.concurrency }} \
      --datadir=/var \
      --docdir=/share/doc \
      --mandir=/share/man \
      --system-zlib \
      --system-bzip2 \
      --system-curl \
      -- \
      -DCMake_BUILD_LTO=ON
    make --jobs {{ hw.concurrency }} install
  env:
    #FIXME tea/cli does this for things that depend on cmake, but not for this
    #FIXME this should at least be moustache variables per pkg
    CMAKE_PREFIX_PATH: /opt/curl.se/v*:/opt/sourceware.org/bzip2/v1:/opt/zlib.net/v1
  error-log:
    Bootstrap.cmk/cmake_bootstrap.log

test:
  script:
    cmake --version
