distributable:
  url: https://download.gnome.org/sources/libxml2/{{ version.major }}.{{ version.minor }}/libxml2-{{ version }}.tar.xz
  strip-components: 1

versions:
  github: GNOME/libxml2/tags
  ignore:
    - v2.10.z  # broken configure (only accepts *specifically* Python 3.1 lol)

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }}
    make install
  env:
    ARGS:
      - --prefix={{prefix}}
      - --without-python  # mysterious build failure in GHA macOS-11

test:
  dependencies:
    tea.xyz/gx/cc: c99
  script: |
    cc `xml2-config --cflags --libs` -o test {{ pkg.pantry-prefix }}/test.c
    ./test
