distributable:
  url: https://github.com/pkgxdev/pkgx/releases/download/v{{ version }}/pkgx-{{ version }}.tar.xz
  strip-components: 1

display-name: pkgx

versions:
  github: pkgxdev/pkgx

provides:
  - bin/pkgx

build:
  dependencies:
    deno.land: ^1.35
  working-directory: ${{prefix}}/bin
  script: |
    sed -i.bak -e 's|tea.xyz|pkgx.sh|g' /opt/tea.xyz/brewkit/v0/share/brewkit/fix-elf.ts
    rm $SRCROOT/deno.lock
    deno task --config "$SRCROOT"/deno.jsonc compile

test:
  test "$(pkgx --version)" = "pkgx {{ version }}"
