distributable:
  url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-{{ version }}.tar.xz
  strip-components: 1

versions:
  github: freedesktop/fontconfig/tags

dependencies:
  sourceware.org/bzip2: 1
  freetype.org: 2
  zlib.net: 1
  gnome.org/libxml2: 2
  libexpat.github.io: 2

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    freedesktop.org/pkg-config: ^0.29
    gnu.org/gperf: 3
    python.org: 3
  script: |
    ./configure --prefix={{ prefix }}
    make --jobs {{ hw.concurrency }} install RUN_FC_CACHE_TEST=false

test:
  fc-list

#TODO
# font_dirs = %w[
#   /System/Library/Fonts
#   /Library/Fonts
#   ~/Library/Fonts
# ]
# font_dirs << Dir["/System/Library/Assets{,V2}/com_apple_MobileAsset_Font*"].max if MacOS.version >= :sierra
