distributable:
  url: https://github.com/mesonbuild/meson/releases/download/{{ version }}/meson-{{ version }}.tar.gz
  strip-components: 1

versions:
  github: mesonbuild/meson/tags

#FIXME
# we need to fix the virtual-env of this thing

dependencies:
  python.org: 3
  #TODO gnu.org/bash

build:
  script: |
    python3 -m venv {{prefix}}/libexec

    cd "{{prefix}}"

    libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed meson
    mkdir bin

    cat <<EOF> bin/meson
      #!/bin/bash
      LIBEXEC="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")"/../libexec/bin && pwd)"
      source "\$LIBEXEC/activate"
      "\$LIBEXEC"/meson "\$@"
    EOF
    chmod ugo+x bin/meson

    cd libexec/bin
    fix-shebangs.ts *

    rm Activate.ps1 activate.csh activate.fish

    sed -i.bak 's|VIRTUAL_ENV=".*"|VIRTUAL_ENV="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. \&\& pwd)"|' activate
    rm activate.bak

    for x in python*; do
      ln -sf ../../../../python.org/v3/bin/$x $x
    done
  #FIXME enable {{ deps.python.org.version.major }}
test:
  dependencies:
    ninja-build.org: 1
    tea.xyz/gx/cc: c99
  script: |
    meson ..
    test -f build.ninja
  working-directory: build
