distributable:
  url: http://ftp.gnu.org/gnu/libtool/libtool-{{ version }}.tar.xz
  strip-components: 1

#FIXME: need versions
versions:
  - 2.4.7

provides:
  - bin/libtool
  - bin/libtoolize

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    gnu.org/autoconf: ^2.65.0
    gnu.org/m4: 1
  script: |-
    ./configure --prefix={{ prefix }}
    make --jobs {{ hw.concurrency }} install

test:
  dependencies:
    tea.xyz/gx/make: '*'
  script: |
    libtoolize
    test -f ltmain.sh