distributable:
  url: https://cache.ruby-lang.org/pub/ruby/{{version.marketing}}/ruby-{{version}}.tar.gz
  strip-components: 1

versions:
  - 3.1.2
  - 2.7.6
  #TODO github: ruby/ruby/tags

dependencies:
  openssl.org: ^1.1
  pyyaml.org: ^0.2
  zlib.net: 1

build:
  dependencies:
    freedesktop.org/pkg-config: ^0.29
    gnu.org/gettext: ^0.21
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |
    ./configure --prefix="{{prefix}}"
    make --jobs {{hw.concurrency}} install

test:
  ruby -e 'puts "Hello World!"'