distributable:
  url: https://pkgconfig.freedesktop.org/releases/pkg-config-{{ version }}.tar.gz
  strip-components: 1

provides:
  - bin/pkg-config

versions:
  github: freedesktop/pkg-config/tags
  strip: /^pkg-config-/

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |-
    ./configure \
      --prefix="{{ prefix }}" \
      --disable-debug \
      --disable-host-tool \
      --with-internal-glib \
      --with-pc-path=/usr/lib/pkgconfig  #FIXME
    make --jobs {{ hw.concurrency }}
    make install

test:
  script: pkg-config --version
