distributable:
  url: https://github.com/gohugoio/hugo/archive/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: gohugoio/hugo

# TODO completion is available by running the command

build:
  script: |
    go build
    mkdir -p "{{ prefix }}"/bin
    mv hugo "{{ prefix }}"/bin
  dependencies:
    go.dev: ^1.18  # probs higher than is true

test:
  hugo version
