distributable:
  url: https://tukaani.org/xz/xz-{{ version }}.tar.gz
  strip-components: 1

versions:
  - 5.2.7
  - 5.2.5

build:
  dependencies:
    tea.xyz/gx/cc: 'c99'
    tea.xyz/gx/make: '*'
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }} install
  env:
    ARGS:
      - --prefix={{ prefix }}
      - --disable-debug
      - --disable-doc

test:
  script: xz --version
