distributable:
  #FIXME url: https://tukaani.org/xz/xz-{{ version }}.tar.gz
  url: https://cytranet.dl.sourceforge.net/project/lzmautils/xz-{{ version }}.tar.gz
  strip-components: 1

versions:
  - 5.2.5

build:
  dependencies:
    tea.xyz/gx/cc: 'c99'
    tea.xyz/gx/make: '*'
  script: |
    ./configure --prefix={{ prefix }} --disable-debug
    make --jobs {{ hw.concurrency }} install

test:
  script: xz --version
