#FIXME
# libjpeg has archaic versioning and we need a mechanism to convert to
# semantic versions with a `versions.ts` script

distributable:
  url: http://jpegclub.org/reference/wp-content/uploads/2022/01/jpegsrc.v9e.tar.gz
  strip-components: 1

versions:
  - 9.5.0

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
  script: |-
    ./configure \
      --disable-dependency-tracking \
      --disable-silent-rules \
      --prefix="{{ prefix }}"
    make --jobs {{ hw.concurrency }} install

test: true  #FIXME
