distributable:
  url: https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1q.tar.gz
  strip-components: 1

versions:
  - 1.1.118
  # TODO
  # github: openssl/openssl
  # parser: version-parser.ts

provides:
  - bin/openssl
  - bin/c_rehash

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    perl.org: 5
  script: |
    case "X{{ hw.target }}" in
      "Xaarch64-apple-darwin")      ARCH="darwin64-arm64-cc";;
      "Xx86_64-apple-darwin")       ARCH="darwin64-x86_64-cc";;
      "Xx86_64-unknown-linux-gnu")  ARCH="linux-x86_64";;
      "Xaarch64-unknown-linux-gnu") ARCH="linux-aarch64";;
    esac

    ./Configure --prefix={{ prefix }} $ARCH no-tests
    make --jobs {{ hw.concurrency }}
    make install

test:
  script: |
    echo "This is a test file" > in
    openssl dgst -sha256 -out out ./in
    test "$(cat ./out)" = "$SAMPLE"
  env:
    SAMPLE: SHA256(./in)= c87e2ca771bab6024c269b933389d2a92d4941c848c52f155b9b84e1f109fe35
