name: new-version
on:
  workflow_dispatch:
    inputs:
      projects:
        description: A JSON string containing repository/version values to build
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      projects: ${{ inputs.projects }}
    secrets: inherit